server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

logging:
  level:
    root: INFO

spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 30005
    host: 210.110.162.185
    password: "password"
