apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-kube-boot
  labels:
    app: boot-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-test
  template:
    metadata:
      labels:
        app: boot-test
    spec:
      containers:
        - name: boot-test
          image: feyndolph/kube_boot:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dk-kube-boot
  labels:
    app: boot-test
spec:
  type: NodePort
  selector:
    app: boot-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 300001
