apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootname
  labels:
    app: bootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootapp
  template:
    metadata:
      labels:
        app: bootapp
    spec:
      containers:
      - name: bootname
        image: feyndolph/kube_boot:1.0
        ports:
        - containerPort: 8080

# nodePort
apiVersion: v1
kind: Service
metadata:
  name:nodeport-service
spec:
  type: NodePort
  selector:
    app: bootapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8080
      